### ISSUE TITLE
JOSS paper examples don't run

### ISSUE THREAD

**Issue by fabian-s** [meixichen/SpatialGEV#13]
Code in your JOSS paper should be executable:

```
> fit <- spatialGEV_fit(y = y, locs = locs, random = "ab",
+                       init_param = list(a = rep(4, n_loc),
+                                         log_b = rep(0,n_loc),
+                                         s = -2,
+                                         beta_a = 4, beta_b = 0,
+                                         log_sigma_a = 0, log_ell_a = 1,
+                                         log_sigma_b = 0, log_ell_b = 1),
+                       reparam_s = "positive", kernel="exp",
+                       X_a = matrix(1, nrow=n_loc, ncol=1),
+                       X_b = matrix(1, nrow=n_loc, ncol=1),
+                       silent=T)                
Error in spatialGEV_fit(y = y, locs = locs, random = "ab", init_param = list(a = rep(4,  : 
  argument "data" is missing, with no default
  ```
  
  openjournals/joss-reviews#6878

**Comment by fabian-s** [comment]
sorry, copy-paste mistake -- nevermind

**Comment by fabian-s** [comment]
PS: 

Your github README.md and your vignette use y as the first argument to spatialGEV_fit, the package and the JOSS paper use data, this seems to have diverged...

**Comment by meixichen** [comment]
> PS:
> 
> Your github README.md and your vignette use y as the first argument to spatialGEV_fit, the package and the JOSS paper use data, this seems to have diverged...

Thank you for the note. Just wanted to clarify, I believe our README on the joss branch (which is for review) is up to date, but I know our master branch is not up to date and we plan to merge joss with master later. Is it possible that you were looking at the master branch? Thanks!

**Comment by fabian-s** [comment]
you're right, sorry for the confusion.
