### ISSUE TITLE
code quality issues 

### ISSUE THREAD

**Issue by fabian-s** [meixichen/SpatialGEV#14]
some issues found by `goodpractice::gp()`, especially test coverage seems way too low.

It is good practice to

  ✖ write unit tests for all functions, and all package code in
    general. 15% of code lines are covered by test cases.

    R/grid_location.R:26:NA
    R/grid_location.R:27:NA
    R/grid_location.R:29:NA
    R/grid_location.R:30:NA
    R/grid_location.R:31:NA
    ... and 482 more lines

  ✖ add a "URL" field to DESCRIPTION. It helps users find
    information about your package online. If your package does not
    have a homepage, add an URL to GitHub, or the CRAN package package
    page.
  ✖ add a "BugReports" field to DESCRIPTION, and point it to a
    bug tracker. Many online code hosting services provide bug trackers
    for free, https://github.com, https://gitlab.com, etc.
  ✖ use '<-' for assignment instead of '='. '<-' is the
    standard, and R users and developers are used it and it is easier
    to read your code for them if you use '<-'.

    tests/testthat/test-model_a_exp.R:25:15
    tests/testthat/test-model_a_matern.R:25:15
    tests/testthat/test-model_ab_exp.R:30:15
    tests/testthat/test-model_ab_matern.R:30:15
    tests/testthat/test-model_abs_exp.R:36:15
    ... and 1 more lines

 
  ✖ avoid sapply(), it is not type safe. It might return a
    vector, or a list, depending on the input data. Consider using
    vapply() instead.

    data-raw/simulatedData2.R:34:17
    R/r_nll.R:91:24
    R/r_nll.R:108:19
    R/r_nll.R:121:19
    R/spatialGEV_fit.R:265:12

  ✖ avoid 1:length(...), 1:nrow(...), 1:ncol(...), 1:NROW(...)
    and 1:NCOL(...) expressions. They are error prone and result 1:0 if
    the expression on the right hand side is zero. Use seq_len() or
    seq_along() instead.

    R/spatialGEV_sample.R:74:25
    R/spatialGEV_sample.R:78:25
    R/spatialGEV_sample.R:83:25
    R/spatialGEV_sample.R:100:16

  ✖ not import packages as a whole, as this can cause name
    clashes between the imported packages. Instead, import only the
    specific functions you need.
 
 
 
see  openjournals/joss-reviews#6878

**Comment by meixichen** [comment]
Thanks a lot for raising these points. I ran `goodpractice::gp()` on the joss branch again after fixing some of these issues, now I only have 
```
It is good practice to

  ✖ avoid long code lines, it is bad for readability. Also,
    many people prefer editor windows that are about 80 characters
    wide. Try make your lines shorter than 80 characters

    data-raw/CA-snowdata.R:25:81
    data-raw/simulatedData.R:18:81
    data-raw/simulatedData.R:27:81
    data-raw/simulatedData.R:29:81
    R/data.R:3:81
    ... and 347 more lines
```

**Comment by fabian-s** [comment]
hmm, I don't see it?

```
10:54 $ git switch joss-devel
Switched to branch 'joss-devel'
(base) ✔ ~/reviews/JOSS/SpatialGEV [joss-devel L|✔] 
10:55 $ R

R version 4.4.0 (2024-04-24) -- "Puppy Cup"
[...]

> goodpractice::gp()
Preparing: covr
Preparing: cyclocomp
Preparing: description
Preparing: lintr
  |======================================================================| 100%
Preparing: namespace
Preparing: rcmdcheck
── GP SpatialGEV ───────────────────────────────────────────────────────────────

It is good practice to

  ✖ write unit tests for all functions, and all package code in
    general. 18% of code lines are covered by test cases.

    R/grid_location.R:22:NA
    R/grid_location.R:23:NA
    R/grid_location.R:25:NA
    R/grid_location.R:26:NA
    R/grid_location.R:27:NA
    ... and 542 more lines

  ✖ avoid long code lines, it is bad for readability. Also,
    many people prefer editor windows that are about 80 characters
    wide. Try make your lines shorter than 80 characters

    data-raw/CA-snowdata.R:25:81
    data-raw/simulatedData.R:18:81
    data-raw/simulatedData.R:27:81
    data-raw/simulatedData.R:29:81
    R/data.R:3:81
    ... and 348 more lines

  ✖ omit trailing semicolons from code lines. They are not
    needed and most R coding standards forbid them

    tests/dontrun/test-spatialGEV_sample.R:7:18

  ✖ avoid sapply(), it is not type safe. It might return a
    vector, or a list, depending on the input data. Consider using
    vapply() instead.

    data-raw/CA-snowdata.R:65:25
    data-raw/simulatedData2.R:34:17
    R/old/spatialGEV_fit.R:265:12
    R/spatialGEV_model.R:92:13
    R/spatialGEV_model.R:98:14
    ... and 6 more lines

  ✖ avoid 1:length(...), 1:nrow(...), 1:ncol(...), 1:NROW(...)
    and 1:NCOL(...) expressions. They are error prone and result 1:0 if
    the expression on the right hand side is zero. Use seq_len() or
    seq_along() instead.

    inst/include/SpatialGEV/templates/make_templates.R:49:11
    R/old/spatialGEV_sample.R:43:25
    R/old/spatialGEV_sample.R:46:25
    R/old/spatialGEV_sample.R:51:25
    R/old/spatialGEV_sample.R:68:16

  ✖ not import packages as a whole, as this can cause name
    clashes between the imported packages. Instead, import only the
    specific functions you need.
```

this is at commit 90dda42 ("resolve issues raised by ...") 

I would also expect you to re-unite diverged branches (at least: master, joss, joss-dev) so that the JOSS publication refers to a (tagged release of the) package that is not some dead end in your development history, and for your JOSS publication to accurately reflect the features etc of that version.

**Comment by fabian-s** [comment]
Can't confirm -- i still see:

```
✖ write unit tests for all functions, and all package code in
    general. 18% of code lines are covered by test cases.

    R/grid_location.R:22:NA
    R/grid_location.R:23:NA
    R/grid_location.R:25:NA
    R/grid_location.R:26:NA
    R/grid_location.R:27:NA
    ... and 543 more lines
```

which seems way too low in terms of test coverage.

I would also like to see you merge all these diverged branches back into master for the JOSS publication so that the JOSS publication does not refer to a dead end in your development history but instead a tagged and accessible release version (or: so that the only divergence is paper/paper.md etc, not anything in your R package code).

**Comment by meixichen** [comment]
Added more unittests and merged joss into master. Now we have a codecov badge in README and test coverage is 89.5% now: https://app.codecov.io/github/meixichen/SpatialGEV.

**Comment by fabian-s** [comment]
Thanks, this fixes all the issues I reported earlier. I'm opening another issue (sorry) for additional problems I found when trying to install the package and rebuild your vignette...
